### ISSUE TITLE
Document deployment workflow

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/vainsocial.com#1]
* use the develop branch of Vaindock and clone vainsocial.com
  * I pushed my customized configuration (changed the volume path and the docker host IP): https://github.com/vainglorygame/laradock/tree/schneefux-local
  * `composer install` in vainsocial.com. PHP logs are in `vainsocial.com/storage/logs/laravel.log`.
  * copy `.env.dev` to `.env` and run `php artisan key:generate`
  * inside the workspace container, run `php artisan migrate:refresh`.
  * assets were not loading, so I changed the `nginx/vainsocial.dev.conf` to serve it at the correct path (see branch mentioned above)

**Comment by kvahuja** [comment]
sounds good. I am taking the /laradock and stripping out everything we don't need in VainSocial.  I am additionally:
1. adding additional PGSQL container so that we have 2 separate DBs running
1.a. giving each of these containers a name so that we can reference easily across machines/platforms
2. will take the Python -> apigrabber code and integrate with /laradock
3. will create a new container for processor (python again)
4. ensure everything works

this will be our VainDock :)

**Comment by kvahuja** [comment]
part of our contribution doc under github-pages repo.
